[package]
name = "testbot"
version = "0.1.0"
authors = ["Yiğit Cemal Öztürk <ozturkyigitcemal@outlook.com.tr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serenity = "0.10.7" 
